plugins {
    id "xyz.wagyourtail.unimined" version "1.4.1"
    id "com.modrinth.minotaur" version "2.+"
}

base.archivesName = project.archives_base_name
version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

unimined.useGlobalCache = false

sourceSets {
    fabric
    ornithe
}

unimined.minecraft {
    version project.minecraft_version

    mappings {
        legacyIntermediary()
        legacyYarn("576")
    }

    fabric {
        loader project.loader_version
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    legacyFabric {
        loader project.loader_version
    }

    defaultRemapJar = true
}

unimined.minecraft(sourceSets.ornithe) {
    combineWith(sourceSets.main)

    ornitheFabric {
        loader project.loader_version
    }

    defaultRemapJar = true
}

processFabricResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
    enabled = false
}
