plugins {
    id "xyz.wagyourtail.unimined" version "1.4.1"
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

base.archivesName = project.archives_base_name
version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

unimined.useGlobalCache = false

sourceSets {
    fabric
    ornithe
}

unimined.minecraft {
    version project.minecraft_version

    mappings {
        legacyIntermediary()
        legacyYarn(project.yarn_mappings_build)
    }

    fabric {
        loader project.loader_version
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    legacyFabric {
        loader project.loader_version
    }

    defaultRemapJar = true
}

unimined.minecraft(sourceSets.ornithe) {
    combineWith(sourceSets.main)

    ornitheFabric {
        loader project.loader_version
    }

    defaultRemapJar = true
}

processFabricResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 8
}

tasks.withType(Jar).configureEach {
    from "LICENSE.txt"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
    enabled = false
}

publishMods {
    type = project.mod_version_type
    changelog = "A changelog can be found at https://github.com/Grayray75/Phosphor-Legacy/releases"

    def baseOptions = modrinthOptions {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "fLCmgUPa"
        minecraftVersions.add(project.minecraft_version)
    }

    modrinth("modrinthFabric") {
        from baseOptions

        file.set(tasks.named("remapFabricJar").flatMap { it.archiveFile })
        displayName = "v${project.mod_version} (${project.minecraft_version}) [LegacyFabric]"

        modLoaders.add("fabric")
        modLoaders.add("legacy-fabric")
    }

    modrinth("modrinthOrnithe") {
        from baseOptions

        file.set(tasks.named("remapOrnitheJar").flatMap { it.archiveFile })
        displayName = "v${project.mod_version} (${project.minecraft_version}) [Ornithe]"

        modLoaders.add("ornithe")
    }
}
