# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version=0.1.4-ornithe
maven_group=io.grayray75.mods
archives_base_name=phosphor-legacy

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.12.2
loader_version = 0.18.1
feather_build = 28
raven_build = 1
sparrow_build = 1
